### ISSUE TITLE
PRACTICE: Write a basic script in SLURM

### ISSUE THREAD

**Issue by andymeneely** [VulnerabilityHistoryProject/mega-foss#1]
To practice our work in SLURM, write a script that will spawn a bunch of jobs that compute something simple. Like a python program that multiplies two numbers, but spread out over multiple nodes/tasks. Check yourself off when this is done. Figure out your workflow (e.g. VS Code via SSH, SSH keys, sporcsubmit bash profile customizations, etc.)

```[tasklist]
### Tasks
- [x] Andy has finished this
- [ ] Tyler has finished this
- [x] Aiden has finished this
```

**Comment by andymeneely** [comment]
Closing so we can move on
